travis:
  secure:
    BINSTAR_TOKEN: WrHHoJVXz9723kkae9CKh0UYYqLAswppCfCpNnX8Qi9OjwM15xfU1YGjMRpOh/qM4H60TKSIOtAHzpDrvS3VmDnGgEKZgbn0cjcFvga+t819GFvq6jFJ66Flq/Q++swDU+y7eh63Cqgf56+JiBoY99JBi37/YJUJEEIY8sSrTQ7FtpiUDlLjpvqO1v7b705Iog9gpuA+RdZNFldwC9mroVUhvWqilhEHDn+vz7IVOvxmWVjypDE2erDQS2ZG3sch5y8Zu1xm0fcyNEzOLvRYeGTw5NgUncbPGH2DudbbTpzhhRFx4mzOiGeU5wYE/hQ9QMF5zQtPeLxOlnqoSCiScstBsX71a21dcBxePHO3mOec4asMBRW11QVVJGiqmHuOVIH5HTjKRNS6sNvaqg5NgcWD1+GlRqLLynkAsBiZwzQWuBEB9FvR7d+A3dpZOQx8v/k1s2JB62WvIPb3a+CWQ620moK+q1xsNG7PA8nPgeXahGXD40Gu494DFH8dUG0ND0N8NuTXghIYrUbuZXOKZMCQDGFjQ6Uh0h9HgzrEf1+2c1Zx0Y4PcPSuRcLQeHZsy/MFAQhljZd00tSm76wTe/MiBQK0YVCOeG56aTa1baq9L0UTjhlRoOdtT8P1YVyaD+3hNnv1hthaqaRAx6HmQqItpPXB376X5lEQWG4pdDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
